In [10]:
import os
import urllib.request
import pandas as pd
import numpy as np


ufos = pd.read_csv('./data/ufos.csv', encoding='cp1252')


ufos.head()

,Date / Time,Country,City,State,Shape,Summary,lat,lng
0,12/21/16 19:15,USA,Waynesboro,VA,Sphere,Bright round object hovering in sky.,38.065229,-78.905888
1,12/21/16 00:00,USA,Louisville,KY,Unknown,Multiple craft ascending from north of Shelbyv...,38.254238,-85.759407
2,12/20/16 22:30,USA,Santa Rosa,CA,Sphere,Bright orange planet-like object sighted near ...,38.440467,-122.714431
3,12/20/16 19:00,USA,Fresno,CA,Circle,Twelve orange globes in formation over Fresno,36.729529,-119.708861
4,12/19/16 21:53,USA,Reymert,AZ,Circle,"While camping in the Cottonwood canyon Rd., al...",33.229779,-111.209290

In [2]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.7.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.22.0 in ./.venv/lib/python3.10/site-packages (from scikit-learn) (2.2.6)
Collecting scipy>=1.8.0 (from scikit-learn)
  Downloading scipy-1.15.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.2.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Downloading scikit_learn-1.7.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (9.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 7.8 MB/s  0:00:01m0:00:0100:01
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading scipy-1.15.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 9.5 MB/s  0:00:036m0:00:0100:01
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Installing collected packages: threadpoolctl, scipy, cloudpickle, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [scikit-learn][0m [scikit-learn]
Successfully installed cloudpickle-3.1.2 joblib-1.6.0 scikit-learn-1.7.2 scipy-1.15.3 threadpoolctl-3.7.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

ufos = pd.read_csv('./data/ufos.csv', encoding='latin-1')
ufos.head()

,Date / Time,Country,City,State,Shape,Summary,lat,lng
0,12/21/16 19:15,USA,Waynesboro,VA,Sphere,Bright round object hovering in sky.,38.065229,-78.905888
1,12/21/16 00:00,USA,Louisville,KY,Unknown,Multiple craft ascending from north of Shelbyv...,38.254238,-85.759407
2,12/20/16 22:30,USA,Santa Rosa,CA,Sphere,Bright orange planet-like object sighted near ...,38.440467,-122.714431
3,12/20/16 19:00,USA,Fresno,CA,Circle,Twelve orange globes in formation over Fresno,36.729529,-119.708861
4,12/19/16 21:53,USA,Reymert,AZ,Circle,"While camping in the Cottonwood canyon Rd., al...",33.229779,-111.209290

In [2]:
# Create the new DataFrame with your available columns
ufos = pd.DataFrame({
    'Country':   ufos['Country'],
    'Latitude':  ufos['lat'],
    'Longitude': ufos['lng'],
})

# Check the unique countries
print(ufos.Country.unique())

['USA' 'CANADA']

In [3]:
ufos.dropna(inplace=True)



print(ufos.shape)
ufos.info()

(5177, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5177 entries, 0 to 5176
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    5177 non-null   object
 1   Latitude   5177 non-null   float64
 2   Longitude  5177 non-null   float64
dtypes: float64(2), object(1)
memory usage: 121.5+ KB

In [4]:
from sklearn.preprocessing import LabelEncoder

ufos['Country'] = LabelEncoder().fit_transform(ufos['Country'])

ufos.head()

   Country   Latitude   Longitude
0        1  38.065229  -78.905888
1        1  38.254238  -85.759407
2        1  38.440467 -122.714431
3        1  36.729529 -119.708861
4        1  33.229779 -111.209290

In [9]:
X = ufos[['Latitude', 'Longitude']]   # dropped 'Seconds'
y = ufos['Country']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0
)

model = LogisticRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)

print(classification_report(y_test, predictions))
print('Accuracy:', accuracy_score(y_test, predictions))

              precision    recall  f1-score   support

           0       0.33      0.11      0.16        28
           1       0.98      0.99      0.98      1008

    accuracy                           0.97      1036
   macro avg       0.65      0.55      0.57      1036
weighted avg       0.96      0.97      0.96      1036

Accuracy: 0.9700772200772201

In [8]:
import pickle

model_filename = 'ufo-model.pkl'
pickle.dump(model, open(model_filename, 'wb'))

# Save the list of country labels so the web app can convert back to names
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder().fit(pd.read_csv('./data/ufos.csv', encoding='latin-1')['Country'])
pickle.dump(le, open('ufo-countries.pkl', 'wb'))

print('Saved:', model_filename, 'and ufo-countries.pkl')

Saved: ufo-model.pkl and ufo-countries.pkl

In [4]:
import pandas as pd

ufos = pd.read_csv('./data/ufos.csv', encoding='latin-1')
print(ufos.columns.tolist())
print(ufos.head())
print(ufos.shape)

['Date / Time', 'Country', 'City', 'State', 'Shape', 'Summary', 'lat', 'lng']
      Date / Time Country        City State    Shape  \
0  12/21/16 19:15     USA  Waynesboro    VA   Sphere
1  12/21/16 00:00     USA  Louisville    KY  Unknown
2  12/20/16 22:30     USA  Santa Rosa    CA   Sphere
3  12/20/16 19:00     USA      Fresno    CA   Circle
4  12/19/16 21:53     USA     Reymert    AZ   Circle

                                             Summary        lat         lng
0               Bright round object hovering in sky.  38.065229  -78.905888
1  Multiple craft ascending from north of Shelbyv...  38.254238  -85.759407
2  Bright orange planet-like object sighted near ...  38.440467 -122.714431
3      Twelve orange globes in formation over Fresno  36.729529 -119.708861
4  While camping in the Cottonwood canyon Rd., al...  33.229779 -111.209290
(5177, 8)

In [1]:
# Install once: pip install chardet
import chardet

with open('./data/ufos.csv', 'rb') as f:
    result = chardet.detect(f.read(100000))
print(result)
# e.g. {'encoding': 'Windows-1252', 'confidence': 0.73, ...}

ModuleNotFoundError: No module named 'chardet'

In [2]:
%pip install chardet

Collecting chardet
  Downloading chardet-7.6.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Downloading chardet-7.6.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 4.0 MB/s  0:00:00 eta 0:00:01
Installing collected packages: chardet
Successfully installed chardet-7.6.0
Note: you may need to restart the kernel to use updated packages.